### ISSUE TITLE
`Out of Bounds` Preview Error on Windows

### ISSUE THREAD

**Issue by Laserwolve** [Laserwolve/DaggerQuest#9]
Previewing the project in Windows gives an `Out of bounds` error on line 25 of `load_loot.gd`:
`var loot_name = file_name.split("_")[1].split("/")[3]`

**Comment by Laserwolve** [comment]
@dhav211, can you see if you can recreate?

**Comment by Laserwolve** [comment]
so `file_name` when the exception is thrown is `res://assets/sprite_sheets/loot/sprites.lootmaraudersbracers_loot-loot-112.5-000.tres`

`.split("_")[1]` should leave us with just `sheets/loot/sprites.lootmaraudersbracers`, which now makes sense that the following `.split("/")[3]` would be out of bounds as there's only 3 values.

@TheDeafCreeper what's `loot_name` ideally supposed to be in this situation? Just `maraudersbracers`?

**Comment by TheDeafCreeper** [comment]
Yeah, I think what's happening is that linux has a trailing slash and windows doesnt. When I print it I get `res://assets/sprite_sheets/loot/sprites.loot/maraudersbracers_loot-loot-112.5-000.tres`

**Comment by TheDeafCreeper** [comment]
May be fixed in [d2f7b97](https://github.com/Laserwolve/DaggerQuest/commit/d2f7b97eb3beeb5f441d045a526fa97a0db26e70)

**Comment by Laserwolve** [comment]
Fixed in https://github.com/Laserwolve/DaggerQuest/commit/d2f7b97eb3beeb5f441d045a526fa97a0db26e70
